### ISSUE TITLE
Add @tscircuit/routing for `schematic_trace` elements

### ISSUE THREAD

**Issue by imrishabh18** [tscircuit/soup-to-svg#4]

**Comment by seveibar** [comment]
@imrishabh18 i don't think you need to do routing because the `schematic_trace` element should be pre-routed:

![image](https://github.com/user-attachments/assets/e4ddf5a4-dbf3-428b-804f-fe6d5c99f496)

**Comment by imrishabh18** [comment]
Yeah, I created this before your comment on the PR. Closing this
